services:

  backend:
    build:
      context: ./Shop
      dockerfile: Dockerfile.txt
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgre;Port=5432;Database=postgres;Username=postgres;Password=postgres
    volumes:
      - /dev/shm:/dev/shm  
    depends_on:
      - postgre
    ports:
      - "8080:8080"

  postgre:
    image: postgres:12.19-alpine3.20
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    labels:
      - "com.example.project=orm"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./resources/init.sql:/docker-entrypoint-initdb.db.d:ro
    ports:
      - "32768:5432"

volumes:
  postgresql_data: {}